//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatGroup
    {
        public ChatGroup()
        {
            this.User_ChatGroup = new HashSet<User_ChatGroup>();
        }
    
        public string NameCG { get; set; }
        public string Logo { get; set; }
        public string Text { get; set; }
        public string File { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Emotion { get; set; }
        public string Image { get; set; }
        public int IdCG { get; set; }
    
        public virtual ICollection<User_ChatGroup> User_ChatGroup { get; set; }
    }
}
