//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ChatSystemEntities1 : DbContext
    {
        public ChatSystemEntities1()
            : base("name=ChatSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chat> Chats { get; set; }
        public DbSet<ChatGroup> ChatGroups { get; set; }
        public DbSet<Request_Demand_User> Request_Demand_User { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<User_ChatGroup> User_ChatGroup { get; set; }
        public DbSet<User_Friend> User_Friend { get; set; }
        public DbSet<User_MobileNumber> User_MobileNumber { get; set; }
    
        public virtual ObjectResult<call_user_specified_Result> call_user_specified(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<call_user_specified_Result>("call_user_specified", useridParameter);
        }
    
        public virtual int DeleteRecordFromReq_Dem_Table(Nullable<int> userRespond)
        {
            var userRespondParameter = userRespond.HasValue ?
                new ObjectParameter("UserRespond", userRespond) :
                new ObjectParameter("UserRespond", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteRecordFromReq_Dem_Table", userRespondParameter);
        }
    
        public virtual int DeleteRecordFromReq_Dem_Table_(Nullable<int> userRequest, Nullable<int> userRespond)
        {
            var userRequestParameter = userRequest.HasValue ?
                new ObjectParameter("UserRequest", userRequest) :
                new ObjectParameter("UserRequest", typeof(int));
    
            var userRespondParameter = userRespond.HasValue ?
                new ObjectParameter("UserRespond", userRespond) :
                new ObjectParameter("UserRespond", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteRecordFromReq_Dem_Table_", userRequestParameter, userRespondParameter);
        }
    
        public virtual int Flag_to_Friend(Nullable<int> userRequest, Nullable<int> userRespond, Nullable<int> flag)
        {
            var userRequestParameter = userRequest.HasValue ?
                new ObjectParameter("UserRequest", userRequest) :
                new ObjectParameter("UserRequest", typeof(int));
    
            var userRespondParameter = userRespond.HasValue ?
                new ObjectParameter("UserRespond", userRespond) :
                new ObjectParameter("UserRespond", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Flag_to_Friend", userRequestParameter, userRespondParameter, flagParameter);
        }
    }
}
