//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int IdSetting { get; set; }
        public Nullable<int> ChatState { get; set; }
        public byte[] BlockList { get; set; }
        public Nullable<int> UserIdSetting { get; set; }
    
        public virtual User User { get; set; }
    }
}
