//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Chats = new HashSet<Chat>();
            this.Request_Demand_User = new HashSet<Request_Demand_User>();
            this.Request_Demand_User1 = new HashSet<Request_Demand_User>();
            this.Settings = new HashSet<Setting>();
            this.User_Friend = new HashSet<User_Friend>();
            this.User_Friend1 = new HashSet<User_Friend>();
            this.User_MobileNumber = new HashSet<User_MobileNumber>();
            this.User1 = new HashSet<User>();
            this.Users = new HashSet<User>();
        }
    
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual ICollection<Request_Demand_User> Request_Demand_User { get; set; }
        public virtual ICollection<Request_Demand_User> Request_Demand_User1 { get; set; }
        public virtual ICollection<Setting> Settings { get; set; }
        public virtual ICollection<User_Friend> User_Friend { get; set; }
        public virtual ICollection<User_Friend> User_Friend1 { get; set; }
        public virtual ICollection<User_MobileNumber> User_MobileNumber { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
